[exchange]
    # Название биржы
    name = "OKX"

[aeron]
    [aeron.subscribers]
        # Продолжительность для стратегии ожидания Aeron в мс
        idle_strategy_sleep_ms = 1

        # Subscriber для приёма биржевого стакана
        [aeron.subscribers.orderbooks]
            channel = "aeron:udp?control-mode=manual"
            stream_id = 1001
            destinations = [
                "aeron:udp?endpoint=172.31.5.122:40458|control=172.31.5.122:40456",
                "aeron:udp?endpoint=172.31.5.122:40459|control=18.159.92.185:40456"
            ]

        # Subscriber для приёма баланса
        [aeron.subscribers.balance]
            channel = "aeron:udp?control-mode=manual"
            stream_id = 1002
            destinations = [
                "aeron:udp?endpoint=172.31.5.122:40460|control=172.31.5.122:40456"
            ]

    [aeron.publishers]
        # Publisher для отправки биржевого стакана
        [aeron.publishers.gateway]
            channel = "aeron:udp?control=172.31.5.122:40456|control-mode=dynamic"
            stream_id = 1003
            buffer_size = 1400

        # Publisher для отправки ошибок
        [aeron.publishers.errors]
            channel = "aeron:udp?control=172.31.5.122:40456|control-mode=dynamic"
            stream_id = 1005
            buffer_size = 1400
